### PR TITLE
Fix high memory issue

### PR DESCRIPTION
**Pull request by djstrong**
Also, I observed some memory leak. However, the best solution would be to not keep a copy of the model in memory and load it from saved filed.

### CODE REVIEW

**Comment by djstrong** [comment]
Unfortunately it didn't help. After about 10 best scores it exceeds 48GB.

**Comment by zphang** [comment]
I can see that deleting `best_state_dict` before re-assigning it will save 1 copy. I do not believe that the number of copies stored in memory should increase over the course of training though (after e.g. the first set of checkpoint-saving). Could you elaborate on your setup?

**Comment by djstrong** [comment]
Yes, it saves one copy. However, I am experiencing some memory leak. The only thing that helped was to change `CPU_DEVICE` to `None` in:
```
            self.best_state_dict = copy_state_dict(
                state_dict=get_model_for_saving(self.model).state_dict(), target_device=CPU_DEVICE,
            )
```
But I am not sure if this change saves a copy properly.

I am training about 10 tasks in parallel with xlm-roberta-large.

**Comment by zphang** [comment]
Could you give more details on your configuration?

- You're training 10 tasks with 1 shared encoder, or 10 tasks in separate processes
- In a process, the CPU memory balloons up to 48gb?

**Comment by djstrong** [comment]
I have tried to reproduce it in Colab with other tasks, but without success.
10 tasks with 1 shared transformer, but different heads. CPU RAM exceeds 48GB. No other modifications, except my own tasks.

**Comment by zphang** [comment]
Would you mind sharing the Colab with me?

**Comment by zphang** [comment]
#187

**Comment by jeswan** [comment]
Fixed with https://github.com/jiant-dev/jiant/pull/187

**Comment by djstrong** [comment]
Thank you, it helped!

**Pull request closed without merging**
