### PR TITLE
add setup.py

### PR DESCRIPTION
**Pull request by jeswan**
This PR adds `setup.py` to package `jiant` for TestPyPi and PyPi. This script has been tested by uploading the output to TestPyPi and installing the package locally. To install a test version of `jiant2` (temporary) with `pip` run the following: 

`pip install -i https://test.pypi.org/simple/ jiant2==2.0.0`

After the install, the package can be imported with `import jiant`.

As a side note, I will need to get access to the `jiant` project on TestPyPi from @davidbenton. I named the project `jiant2` in the meantime for testing. @sleepinyourhat - I leveraged https://github.com/nyu-mll/jiant-v1-legacy/blob/master/setup.py to for the license, authors, etc.

### CODE REVIEW

**Comment by davidbenton** [comment]
Can do, @jeswan! I think you'll need to create a TestPyPI account if you don't have one and send me the username so I can add you. @sleepinyourhat since you were my main contact when setting that account up, would you verify that I can add @jeswan as owner of the package on TestPyPI?

**Comment by sleepinyourhat** [comment]
Please do. Many thanks!

**Comment by jeswan** [comment]
Thanks @davidbenton! My username is: jeswan.

**Review by zphang — APPROVED** [review]

**Comment by davidbenton** [comment]
Invitation sent! Once you're added, you can go ahead and delete me, @jeswan

**Pull request merged**
